[package]
name = "stars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
crossterm = "0.26.1"
petgraph = "0.6.3"
tui = "0.19.0"
unicode-width = "0.1.10"
